### PR TITLE
fix(initials): implement getInitials utility function

### LINKED ISSUE #510: Avatar UI shows too many initials
The avatar circle currently renders the first letter of every word in the user's display name. For names with multiple parts (e.g. "John Doe Something Something"), this produces a cluttered "JDSS" that overflows the small circle.

We should have it display at most 2 initials: the first letter of the first name and the first letter of the last name.

### PR DESCRIPTION
**Pull request by Spafic**
- closes #510 
- Fixed and centralized initials for future usage

### CODE REVIEW

**Comment by ashmod** [comment]
Nice, can you add tests?

File: apps/web/src/lib/initials.ts
Comment (ashmod) [inline apps/web/src/lib/initials.ts:1]: we can move that outside of utils for now since we're following that convention where utility methods and their tests live inside `lib/`.

File: apps/web/src/lib/utils/initials.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * Returns the initials of a given name.
+ * - If the name is empty, returns "U".
+ * - For names with multiple words, returns the first letter of the first and last name.
+ * - For single-word names, returns just the first letter.
+ * @param name The full name string.
+ * @returns The initials (up to 2 uppercase letters), or "U" if not available.
+ */
+export const getInitials = (name: string): string => {
+  if (!name) return "U";
+  const parts = name.split(" ").filter((part) => part.length > 0);
```
Comment (ashmod) [inline apps/web/src/lib/utils/initials.ts]: `split(" ")` would miss tabs and multi-space edge cases, consider replacing with
```ts
name.trim().split(/\s+/)
```
which also removes the need for the `.filter`

Comment (Spafic) [reply apps/web/src/lib/utils/initials.ts]: Nice catch, Thank u ❤️

Comment (Spafic) [reply apps/web/src/lib/utils/initials.ts]: The filter part is important; if the name is "         ", the avatar will be blank
image

Surprisingly, backend accepts empty strings 🥳

Comment (ashmod) [reply apps/web/src/lib/utils/initials.ts]: Well.. that shouldn't be allowed :D

You could open an issue on that backend problem.

Comment (Spafic) [reply apps/web/src/lib/utils/initials.ts]: I will and keep the filter as a final frontend validation :)

**Review by ashmod — APPROVED** [review]
LGTM
